### ISSUE TITLE
Checkpoint restore

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#237] opened 2023-05-25 18:16 UTC
This feature allows us to "reboot" the network from a given point in time, preserving state such as the set of validators and coin balances, after a catastrophic failure (e.g., no validators for an epoch).

* [x] https://github.com/spacemeshos/go-spacemesh/issues/4090

**Comment by lrettig** [comment] 2023-06-22 18:03
This was tested today on testnet-05 for the first time.

**Comment by lrettig** [comment] 2023-06-27 19:09
@countvonzero @pigmej is anything still pending here on the tech side, other than additional testing?

**Comment by pigmej** [comment] 2023-06-27 19:28
Yes, today we discovered that issue with CommitementAtx. (Needs to be filled still).
Definitely will need to be fixed.

Cc @fasmat @poszu

**Comment by countvonzero** [comment] 2023-06-27 20:38
if you want to use this to track bug fixes, you will never close this issue.

**Comment by countvonzero** [comment] 2023-06-27 20:39
removing myself, as i am not PMing this issue.

**Comment by pigmej** [comment] 2023-06-27 21:02
> if you want to use this to track bug fixes, you will never close this issue.

This is PM issue. We noticed that serious enough bug that affects a lot of people..imho worth tracking is here unless at least the issue is filled.

I would not reopen it if it would be closed already though :)

**Comment by pigmej** [comment] 2023-07-24 14:01
The issues are filled, we can close that one for now. Makes the picture more clear and less confusing.

- [ ] https://github.com/spacemeshos/go-spacemesh/issues/4624
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/4540
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/4625

**Closed as completed by pigmej** 2023-07-24 14:01 UTC
Labels: milestone/genesis
